export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
export const FETCH_EXPERIMENT = 'FETCH_EXPERIMENT';
export const EDIT_EXPERIMENT = 'EDIT_EXPERIMENT';
export const SORT_EXPERIMENTS = 'SORT_EXPERIMENTS';
export const TOGGLE_SORT_ORDER = 'TOGGLE_SORT_ORDER';
export const TOGGLE_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const FILTER_EXPERIMENTS = 'FILTER_EXPERIMENTS';
